### ISSUE TITLE
NoSuchMethodError with Velocity dev build

### ISSUE THREAD

**Issue by mikroskeem** [mikroskeem/Adminchatter#6]
```
[01:25:33 ERROR]: Some errors occurred whilst posting event PlayerChatEvent{player=[connected player] mikroskeem (/redacted), message=@t, result=denied}.
[01:25:33 ERROR]: #1:

java.lang.NoSuchMethodError: 'net.kyori.adventure.text.ComponentBuilder net.kyori.adventure.text.TextComponent$Builder.hoverEvent(net.kyori.adventure.text.event.HoverEvent)'
        at eu.mikroskeem.adminchatter.common.ChannelChatKt.sendChannelChat(ChannelChat.kt:63) ~[?:?]
        at eu.mikroskeem.adminchatter.common.ChannelChatKt.handleToggleChat(ChannelChat.kt:134) ~[?:?]
        at eu.mikroskeem.adminchatter.velocity.listeners.ChatListener.on(ChatListener.kt:54) ~[?:?]
        at net.kyori.event.asm.generated.9283489947.ChatListener-on-PlayerChatEvent-21.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[server.jar:1.1.0-SNAPSHOT (git-7650eedb-bunknown)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[server.jar:1.1.0-SNAPSHOT (git-7650eedb-bunknown)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:139) ~[server.jar:1.1.0-SNAPSHOT (git-7650eedb-bunknown)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:120) ~[server.jar:1.1.0-SNAPSHOT (git-7650eedb-bunknown)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by mikroskeem** [comment]
Also build fails with following message:
```
> Task :common:compileKotlin FAILED
e: /Users/mark/IdeaProjects/adminchatter/common/src/main/kotlin/eu/mikroskeem/adminchatter/common/ChannelChat.kt: (63, 28): Overload resolution ambiguity:
public open fun hoverEvent(source: HoverEventSource<*>): TextComponent.Builder defined in net.kyori.adventure.text.TextComponent.Builder
public abstract fun hoverEvent(event: HoverEvent<*>?): TextComponent.Builder defined in net.kyori.adventure.text.TextComponent.Builder
```
